[tool.pytest.ini_options]
log_auto_indent = true

log_cli = true
log_cli_level = "DEBUG"
log_cli_format = "%(asctime)s %(levelname)-7s %(message)s"
log_cli_date_format = "%Y-%m-%d %H:%M:%S"
# How to manage logging
log_file = "pytest.log"
log_file_mode = "a"
log_file_level = "DEBUG"
log_file_format = "%(asctime)s %(levelname)-7s %(message)s"
log_file_date_format = "%Y-%m-%d %H:%M:%S"
testpaths = [
    "tests"
]
addopts="-color=auto --no-header -r=N --show-capture=no --setup-show --showlocals -vv"