name: GoogleTest

on:
  push:
    branches: [ master ]

jobs:
  gtest:
    name: Launch GoogleTest
    strategy:
      matrix:
        os: [macos-latest]
    runs-on: ${{ matrix.os }}
    env:
      buildDir: "${{ github.workspace }}/build"

    steps:
      - name: Project checkout
        uses: actions/checkout@v3

      - name: Get latest CMake and ninja
        # Using 'latest' branch, the most recent CMake and ninja are installed.
        uses: lukka/get-cmake@latest

      - name: CMake configure
        run: cmake --log-level=DEBUG -Wdev -DCMAKE_BUILD_TYPE=Debug -S . -B ${{ env.buildDir }}

      - name: CMake build
        run: cmake --build ${{ env.buildDir }}

      - name: Run leetcode
        run: ${{ env.buildDir }}/tests/leetcode/tests_leetcode
