name: pytest

on:
  push:
    branches: [ python ]

jobs:
  pytest:
    name: Launch pytest
    strategy:
      matrix:
        os: [ macos-latest ]
    runs-on: ${{ matrix.os }}
    env:
      PIPENV_VERBOSITY: -1

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - run: |
          python -m pip install --upgrade pipenv
      - run: |
          pipenv install
      - run: |
          pipenv run pytest
